version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy
    overwrite: yes

permission:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 80
  AfterInstall:
    - location: script/start.sh
      timeout: 80
      runas: root
  ValidateService:
    - location: script/valid.sh
      timeout: 100
      runas: root