spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: kimhyunki
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create  #테이블 자동생성
    properties:
      hibernate:
        #show_sql: true #System.out에 찍음 운영환경에서는 찍으면 안됨. logger를 통해서 찍어야함.
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #hibernate SQL모드를 debug로 사용함 로거를 통해 찍음.
    org.hibernate.type: trace # SQL의 쿼리 파라미터를 찍어줌.