name: 🚀MAKERS-APP-RELEASE!

on:
  push:
    branches: [ 'feature/github-actions' ]
    tags: [ 'makers-app-develop' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 🐈 Gradle Build
        run: ./gradlew clean build

      - name: Make Directory
        run: mkdir deploy

      - name: 🔧 Copy Jar
        run: cp ./build/libs/*.jar ./deploy

      - name: 📂 Make zip file
        run: zip -r ./app-server.zip ./deploy

      - name: 🪣 S3 upload
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: 🚀 s3 upload
        run: aws s3 cp --region ap-northeast-2 --acl private ./app-server.zip s3://sopt-makers/deploy


